### ISSUE TITLE
[BUG] STACK_VERSION=1.2.4 cargo make test fails

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-rs#115]
### What is the bug?

In dev guide we tell devs to run `STACK_VERSION=1.2.4 cargo make test`. It fails. The first problem is that the docker image brought up has SSL enabled, so the default http://localhost:9200 doesn't work. Changing it to https://localhost:9200 in Cargo.toml gets further, but some certificate tests are still failing.

### How can one reproduce the bug?

1. Check out code.
2. `STACK_VERSION=1.2.4 cargo make test`

### What is the expected behavior?

Tests to pass.

### What is your host/environment?

```
$ uname -a
Darwin b0f1d8717713 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000 arm64
```

**Comment by Xtansia** [comment]
After several recent PRs these steps should now work as expected
