### ISSUE TITLE
[BUG] Remove references to old PIT APIs 

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-rs#135]
### What is the bug?
`open_point_in_time` and `close_point_in_time` APIs are not supported by OpenSearch. See https://github.com/opensearch-project/opensearch-ruby/pull/155#discussion_r1143922457

Remove the following references: https://github.com/search?q=repo%3Aopensearch-project%2Fopensearch-rs+pit&type=code

### How can one reproduce the bug?
This client does not support these APIs, there are just some dangling references in specs.

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by Swiddis** [comment]
Working on this
