### ISSUE TITLE
Cleanup unused branches

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-rs#257]
Coming from https://github.com/opensearch-project/opensearch-clients/issues/64, cleanup unused branches.

For some unused branches we probably want to save state, so maybe note the last revision of any branch being deleted in this issue as it's being closed.

**Comment by Xtansia** [comment]
The repo has the following stale/no-longer in-dev branches:
* `7.10`: 4fb78c30dc2e6292bce49e3e15c817e98bca829a
* `1.0`: a8e8f6508dac2c65916b5839363ebe2edcd81037
* `1.x`: 7bb8b906d8da6856017bd4428f61f12edbf8f162
* `2.0`: 38c0b6766e0f2b3d17fabdd3a7274210bfb0f2f8
* `2.1`: edb021d09ae98430014265d9b1f147945a3184f2
* `2.1.0`: 4d9e364a044f8c39cb9233839663f8220d2daa3f

**Comment by Xtansia** [comment]
The above branches have now been cleaned up thanks to @gaiksaya
