### ISSUE TITLE
Proposal: AWS4 signatures signing

### ISSUE THREAD

**Issue by rosscanning** [opensearch-project/opensearch-rs#36]
I need signed Opensearch requests to AWS, using AWS4 signatures. The Rust code to implement this is available (there are a couple of standalone crates, or we could extract it from the Rust AWS SDK). I would be willing to do the work, if you are willing to consider an PR. I'd welcome suggestions on how to implement, which signing code to use, how the API should work, etc.

**Comment by dblock** [comment]
Would definitely appreciate a PR!

**Comment by rosscanning** [comment]
@Xtansia Thanks!

**Comment by Xtansia** [comment]
@rosscanning Apologies for stepping on your toes on this one! I should have checked in with you first

**Comment by rosscanning** [comment]
@Xtansia No problem at all! Your implementation is better than mine, anyway :)
