### ISSUE TITLE
[PROPOSAL] Run integration tests against multiple versions of OpenSearch

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-rs#43]
### What kind of business use case are you trying to solve? What are your requirements?
Compatibility with OpenSearch is unclear.

### What is the problem? What is preventing you from meeting the requirements?
I can't tell which version of the client supports which version of OpenSearch.

### What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?
- Add integration tests against multiple versions of OpenSearch similar to https://github.com/opensearch-project/opensearch-java/pull/154
- Document compatibility similar to https://github.com/opensearch-project/opensearch-java#compatibility-with-opensearch.

**Comment by VachaShah** [comment]
Duplicate of #37
