### ISSUE TITLE
[FEATURE] AWS authentication from a borrowed SdkConfig

### ISSUE THREAD

**Issue by gmacon** [opensearch-project/opensearch-rs#62]
### Is your feature request related to a problem?
I'm in a context where I have a borrow of a pre-existing [`SdkConfig`](https://docs.rs/aws-config/latest/aws_config/struct.SdkConfig.html); currently, converting that into [`Credentials`](https://docs.rs/opensearch/latest/opensearch/auth/enum.Credentials.html) requires an *owned* `SdkConfig`, so I need to clone it:

```rust
fn opensearch_client(url: &str, aws_config: &SdkConfig) -> Result<Opensearch> {
    let conn_pool = SingleNodeConnectionPool::new(url.parse()?);
    let transport = TransportBuilder::new(conn_pool).auth(aws_config.clone().try_into()?).build()?
    Opensearch::new(transport)
}
```

### What solution would you like?
I'd like to add a `impl TryFrom<&SdkConfig> for Credentials` block. From a quick look at the code, it doesn't appear that the current `impl TryFrom<SdkConfig> for Credentials` actually needs to take ownership, so I would collapse it to just call the borrowed version.

### What alternatives have you considered?
* Do nothing. Cloning works just fine, but feels unnecessary.

### Do you have any additional context?
No.

**Comment by wbeckler** [comment]
Would this change break the applications that people have already written with this client?

**Comment by gmacon** [comment]
I'm not proposing to remove the existing `impl From<SdkConfig> for Credentials`, so I wouldn't expect any breakage, though I suppose it's possible that Clippy might start complaining about unnecessary clones or something along those lines.

**Comment by dblock** [comment]
Do PR this @gmacon!
