### ISSUE TITLE
[FEATURE] Add info object

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-rs#94]
### Is your feature request related to a problem?

Fetching server info at root doesn't return a structure.
 
### What solution would you like?

```rs
let info: Info = client.info().send().await?.json().await?;
```

### What alternatives have you considered?

Currently I'm doing one of these:

```rs
    let info: Value = client.info().send().await?.json().await?;
    println!("{}: {}", info["version"]["distribution"].as_str().unwrap(), info["version"]["number"].as_str().unwrap());
```

```rs
    #[derive(Serialize, Deserialize)]
    struct Version {
        distribution: String,
        number: String
    }

    #[derive(Serialize, Deserialize)]
    struct Info {
        version: Version
    }

    let info: Info = client.info().send().await?.json().await?;
    println!("{}: {}", info.version.distribution, info.version.number);
```

Is there an existing better way, otherwise I'll try to queue up a PR. Also not sure what the right way to add this is, pointers appreciated.

**Comment by Refffy** [comment]
Hey! I'll work on the issue.

**Comment by samuelorji** [comment]
@Xtansia can i pick this next ?

**Comment by samuelorji** [comment]
draft: https://github.com/opensearch-project/opensearch-rs/pull/187 with some questions
